### ISSUE TITLE
BOOT OPENCORE ISSUE

### ISSUE THREAD

**Issue by itsrosariomarciano** [xWeapon/CoreBook_X_OC#1]
With the previous folder it works perfect..With this one i can't boot to install Mac Os... I just see Windows on the opencore menu. Pls, post online the previous folder!

**Comment by xWeapon** [comment]
Weird.
Just restored the old one you can clone it from here now.

For the future this repo is not supposed to be placed on your working machine, but just as a start point to follow and understand the Dortania Guide to OpenCore.

Your error seems to be something related to Misc>Security>Scan Policy[value] or something related to the AHCI controller (look fo AHCICatalina) or also the way you erased your disk.
In any case make sure to follow Dortania Guide here is every thing helped me making that repo.

**Comment by itsrosariomarciano** [comment]
Yesterday someone linked me the previous folder, so i was able to reinstall it. However my laptop is a corebook x by chuwi so i think that is not a problem of file. I want to ask you a question. If i want to upgrade with the new folder how i can do? I saved the past folder on a cloud so if there will be some issues i will solved the problem.

**Comment by xWeapon** [comment]
Nothin, just remember to learn from Dortania.
I'm going to provide a Guide for USERS.
Currently I don't have time, for work reasons, follow my repo or star it to receive updates.
Issue closed.
